ARG IMAGE_TAG
FROM ghcr.io/dusansimic/toolbox-images/base:${IMAGE_TAG}

ARG IMAGE_TAG
ENV NAME=rstudio-toolbox VERSION=${IMAGE_TAG}
LABEL com.github.containers.toolbox="true" \
  com.redhat.component="$NAME" \
  name="$NAME" \
  version="$VERSION" \
  usage="This image is meant to be used with the toolbox command" \
  summary="RStudio image for my personal Fedora toolbox containers" \
  maintainer="Dušan Simić <dusan.simic1810@gmail.com>"

COPY README.md /README-rstudio.md

RUN dnf install 'dnf-command(copr)'
RUN dnf copr enable -y iucar/cran

COPY extra-packages /
RUN dnf -y install $(<extra-packages)
RUN rm /extra-packages

RUN dnf clean all
