ARG IMAGE_TAG
FROM registry.fedoraproject.org/fedora-toolbox:${IMAGE_TAG}

ARG IMAGE_TAG
ENV NAME=base-toolbox VERSION=${IMAGE_TAG}
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for my personal Fedora toolbox containers" \
      maintainer="Dušan Simić <dusan.simic1810@gmail.com>"

COPY README.md /README-base.md

RUN dnf install 'dnf-command(config-manager)'
RUN dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo

COPY extra-packages /
RUN dnf -y install $(<extra-packages)
RUN rm /extra-packages

COPY swap-packages /
RUN while IFS= read -r line; do dnf -y swap $line; done < swap-packages
RUN rm /swap-packages

RUN mkdir -p /opt/oha/bin
ADD https://github.com/hatoo/oha/releases/download/v1.4.4/oha-linux-amd64 /opt/oha/bin/oha
RUN chmod +x /opt/oha/bin/oha
ENV PATH="${PATH}:/opt/oha/bin"

ADD https://github.com/bootandy/dust/releases/download/v1.0.0/dust-v1.0.0-x86_64-unknown-linux-gnu.tar.gz /tmp/dust.tar.gz
RUN mkdir /tmp/dust
RUN tar -xf /tmp/dust.tar.gz -C /tmp/dust --strip-components=1
RUN mkdir -p /opt/dust/bin
RUN mv /tmp/dust/dust /opt/dust/bin/dust
RUN chmod +x /opt/dust/bin/dust
RUN rm -rf /tmp/dust /tmp/dust.tar.gz
ENV PATH="${PATH}:/opt/dust/bin"

RUN mkdir -p /opt/translitrs/bin
ADD https://github.com/filiparag/translitRS/releases/download/0.2.2/translitrs-0.2.2-gnu_linux-x86_64 /opt/translitrs/bin/translitrs
RUN chmod +x /opt/translitrs/bin/translitrs
ENV PATH="${PATH}:/opt/translitrs/bin"

ENV LC_ALL=en_US.UTF-8

RUN dnf clean all
