name: Java image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/java.yml
      - images/java/**
  workflow_dispatch:

jobs:
  build:
    name: Build Java image
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      image-name: java
      image-tag: "40"
      containerfile-path: images/java
      context-path: images/java
