name: Node.js image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/node.yml
      - images/node/**
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: node

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=match,pattern=(\d+),group=1,value=38
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ env.IMAGE_NAME }}
          file: ./images/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ steps.meta.outputs.tags }}
