name: Node.js image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/node.yml
      - images/node/**
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Node.js image
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      image-name: node
      image-tag: "40"
      containerfile-path: images/node
      context-path: images/node
