name: RStudio image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/rstudio.yml
      - images/rstudio/**
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rstudio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=(\d+),group=1,value=38
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ env.IMAGE_NAME }}
          file: ./images/${{ env.IMAGE_NAME }}/Containerfile
          push: true
          no-cache: true
          tags: |
            ${{ steps.meta.outputs.tags }}
