name: RStudio image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/rstudio.yml
      - images/rstudio/**
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build RStudio image
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      image-name: rstudio
      image-tag: "40"
      containerfile-path: images/rstudio
      context-path: images/rstudio
